In [ ]:
numerical python
NumPy (Numerical Python) is a fundamental Python library used for scientific computing, 
data analysis, and numerical operations. It provides fast and efficient tools for working 
with large datasets, especially arrays and matrices.

In [ ]:
1. Fast Computation

NumPy uses optimized C code under the hood, making operations
much faster than pure Python lists.
NumPy provides built-in functions for:

Linear algebra

Statistics

Random number generation

Vectorized operations (no slow Python loops!)


Foundation for Many Libraries

Libraries like Pandas, SciPy, scikit-learn, TensorFlow, and PyTorch depend heavily on NumPy.

In [ ]:
Vectorized operations in NumPy mean performing operations on entire arrays at once, 
without writing explicit Python loops.

In [ ]:
# numpy vs list
faster
convenient
less memory

In [16]:
import numpy as np
import sys
import time

In [14]:
l = range(100)
array = np.arange(100)
#l → Python range object (lazy sequence)
#array → NumPy array (all elements stored in memory)

In [17]:
print(sys.getsizeof(l))
#Output is typically 48–56 bytes (independent of length)
#Range does not store all elements

48


In [18]:
# numpy memory size
print(array.nbytes)
#Output: 100 elements × 8 bytes (int64) = 800 bytes (depends on dtype)
#NumPy stores all elements in memory

800


In [ ]:
# conclusion 
range is extremely memory-efficient, even for huge ranges.

In [ ]:
# vectorizrd operation

In [ ]:
# in python 
a = [1, 2, 3]   # *3
result = []

for x in a:
    result.append(x * 3)

print(result)

In [ ]:
#Multiply every element by 3
a = np.array([1, 2, 3])
a
a * 3
# [3 6 9]

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a = a * 2

In [ ]:
# in python
A = [[1, 2, 3],
     [4, 5, 6]]

for i in range(len(A)):
    for j in range(len(A[i])):
        A[i][j] = A[i][j] * 2

print(A)

In [ ]:
a ** 2

In [8]:
import numpy as np

In [ ]:
# add two array
a + b

In [19]:
#with broadcasting
#NumPy expands b automatically to match A.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

A + b

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
# in python 
result = []
for row in A:
    new_row = []
    for i in range(len(b)):
        new_row.append(row[i] + b[i])
    result.append(new_row)

print(result)

In [ ]:
# boolean indexing

In [59]:
#NumPy expands b automatically to match A.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A[A > 3]
# element-wise comparison

array([4, 5, 6])

In [22]:
# in python 
A = [[1, 2, 3],
     [4, 5, 6]]

result = []
for row in A:
    new_row = []
    for x in row:
        new_row.append(x > 3)
    result.append(new_row)

print(result)

[[False, False, False], [True, True, True]]


# numpy Important Attributes/Methods

In [ ]:
Summary Table
Category	                    Important Attributes/Methods

Attributes               	    ndim, shape, size, dtype, itemsize, nbytes, T
Creation	                     array, zeros, ones, full, arange, linspace, eye
Manipulation	               reshape, flatten, transpose, stacking & splitting
Math	                       sum, mean, min, max, std, argmax, cumsum
Logic	                       comparisons, any, all
Indexing	                  slicing, boolean mask, fancy indexing
Linear algebra	                inv, det, eig, solve, dot

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ndim  

2

In [25]:
#shape — tuple showing rows & columns
a.shape     # (2, 3)

(2, 3)

In [26]:
#size — total number of elements
a.size      # 6

6

In [27]:
#dtype — data type of elements
a.dtype     # int32, float64, etc.

dtype('int64')

In [29]:
#T — transpose (attribute)
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
#astype--- to convert the datatype
a.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# array creation method

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [34]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.full((3,3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [39]:
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Range-based

In [40]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [42]:
np.linspace(1, 10, 5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
#Identity matrices

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Array Manipulation Methods

In [46]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [50]:
#Reshaping
a.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
Flattening

In [51]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
Transpose

In [54]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
a.transpose()

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [55]:
b=np.array([[[4,2],[6,4]],[[5,6],[17,8]]])
b

array([[[ 4,  2],
        [ 6,  4]],

       [[ 5,  6],
        [17,  8]]])

In [ ]:
Stacking

In [56]:
np.hstack([a, b])

array([[[ 1,  2],
        [ 3,  4],
        [ 4,  2],
        [ 6,  4]],

       [[ 5,  6],
        [ 7,  8],
        [ 5,  6],
        [17,  8]]])

In [57]:
np.vstack([a, b])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 4,  2],
        [ 6,  4]],

       [[ 5,  6],
        [17,  8]]])

In [58]:
np.stack([a, b], axis=0)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 4,  2],
         [ 6,  4]],

        [[ 5,  6],
         [17,  8]]]])

# statistics


In [ ]:
import numpy as np

In [66]:
data = np.array([10, 20, 30, 40, 50])
np.mean(data)

np.float64(30.0)

In [67]:
np.median(data)

np.float64(30.0)

In [ ]:
np.min(data)   # or data.min()
np.max(data)   # or data.max()

In [ ]:
np.percentile(data, 25)  # 25th percentile  means 25% people is lagging behind you
np.percentile(data, 75)  # 75th percentile

In [ ]:
np.sum(data)   # 150
np.prod(data)  # 12000000

In [ ]:
np.arange(0,10,2) → Array from 0 to 8 with step 2
np.linspace(0,1,5) → 5 evenly spaced numbers between 0 and 1


In [ ]:
Broadcasting
Allows operations on arrays of different shapes.
NumPy automatically expands the smaller array along missing dimensions

In [ ]:
Array–Array Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y        # [5, 7, 9]
x * y        # [4, 10, 18]
x-y
x>3
x*2

In [ ]:
Matrix Operations

In [71]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
#a.dot(b)
#A @ B               # matrix multiplication
np.dot(A, B)        # same


array([[19, 22],
       [43, 50]])

In [ ]:
Concatenation
Joining arrays together.

In [75]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [73]:
# 1D concatenation
c = np.concatenate([a, b])
print(c)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [77]:
# 2D concatenation
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# concatenate along rows (axis=0)
#C = np.concatenate([A, B], axis=0)
#print(C)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
# concatenate along columns (axis=1)
D = np.concatenate([A, B], axis=1)
print(D)
# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [81]:
arr1.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
indexing,slicing,iteration

In [90]:
a = np.array([10, 20, 30, 40])
a[0]     # 10
a[-1]    # 40

np.int64(40)

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A[0, 0]  # 1  (row 0, col 0)
A[1, 2]  # 6  (row 1, col 2)
A[2, -1] # 9  (last column)

In [92]:
a

array([10, 20, 30, 40])

In [91]:
# slicing 
a[1:3]   # [20, 30]
#a[:3]    # first 3 elements
#a[::2]   # every second element

array([20, 30])

In [93]:
A

array([[1, 2],
       [3, 4]])

In [96]:
#A[r1:r2 , c1:c2]
A[1:2, 0:1]

array([[3]])

In [97]:
A[0, :]   # row 0

array([1, 2])

In [ ]:
A[:, 1]   # column 1
A[1:, :]  # all rows except first
A[:,2]    #all row,2 col
A[:2]      #0,1 row
A[:,1:3]  #all row,1,2 col
A[2:4,1:3] # 4 SKIP,3 skip 

In [ ]:
Fancy Indexing
rows = np.array([0, 2])
cols = np.array([1, 2])

In [ ]:
Pick rows 0 and 2:
A[[0, 2]]
# [[1, 2, 3],
#  [7, 8, 9]]

In [106]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
A[[0, 2], :][:, [1, 2]]
# pick rows 0 & 2, and columns 1 & 2

array([[2, 3],
       [8, 9]])

In [109]:
arr1=np.arange(24).reshape(6,4)
print(arr1)
print(arr1[[0,2,4],:][:,[1,2]])
arr1[:,[0,2,3]] # : means all row 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 1  2]
 [ 9 10]
 [17 18]]


array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# numpy function

In [ ]:
Random Number Functions (np.random)
Function	Purpose	Example
np.random.rand()	Uniform [0,1)	np.random.rand(3,2)
np.random.randn()	Standard normal	np.random.randn(3,2)
np.random.randint()	Random integers	np.random.randint(0,10,5)
np.random.choice()	Random selection	np.random.choice([1,2,3],3)
np.random.seed()	Fix random seed	np.random.seed(42)

In [118]:
np.random.rand(3,3)

array([[0.5249915 , 0.75462513, 0.18097214],
       [0.88496502, 0.84360504, 0.16171687],
       [0.05780147, 0.68019652, 0.65430878]])

In [117]:
np.random.randn(3,2)

array([[-0.20708208,  0.95742044],
       [ 0.21440662,  0.36825573],
       [ 1.13586519, -0.20072083]])

In [131]:
np.random.randint(0,100,5)

array([20, 82, 86, 74, 74], dtype=int32)

In [125]:
np.random.choice([1,2,3,4,5,6],1)

array([6])

In [130]:

np.random.seed(42)
np.random.randint(0,100,5)

array([51, 92, 14, 71, 60], dtype=int32)


# sorted  return python list 


In [113]:
a = np.random.randint(1, 100, 15)
print(a)
np.sort(a)#Returns a sorted copy of a (does not modify a in-place).
sorted_list = np.sort(a).tolist()

[ 4 98 30 19 30 94 63 91 24 51 14 47 49 91 73]


In [115]:

b = np.array([[12, 55, 3],
              [78, 45, 7],
              [33, 90, 21]])
#Sort along axis=0 (down the rows, i.e., column-wise)
np.sort(b, axis=0)
#Sorts each column independently.

array([[ 3, 12, 55],
       [ 7, 45, 78],
       [21, 33, 90]])

In [ ]:
Sort along axis=1 (across columns, i.e., row-wise)
np.sort(b, axis=1)

In [ ]:
np.sort() returns a sorted copy; original array is unchanged.

Use a.sort() to sort in-place (modifies a).

Works for any-dimensional array, using axis to control direction.